[package]
name = "rudis"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.12.1"
clap = { version = "4.6.6", features = ["derive"] }
core_affinity = "0.8.3"
crc16 = "0.4.0"
flume = "0.12.0"
hashbrown = "0.17.1"
fxhash = "0.2.1"
mimalloc = { version = "0.1.52", default-features = false }
monoio = { version = "0.2.4", features = ["sync"] }
socket2 = { version = "0.6.5", features = ["all"] }
mlua = { version = "0.12.1", features = ["lua54", "vendored"] }
sha1 = "0.11.0"
libc = "0.2"
tikv-jemallocator = { version = "0.7.0", features = ["stats", "background_threads_runtime_support"] }
tikv-jemalloc-ctl = { version = "0.7.0", features = ["stats", "use_std"] }
rustls = "0.23.45"
rustls-pki-types = { version = "1.15.1", features = ["std"] }
rcgen = "0.14.10"

