#!/usr/bin/env python3
"""Generate src/acl_categories.rs: the ACL command/category table.

Source of truth is the Valkey command table (src/commands/*.json), with the
same implicit-category rules Valkey applies at startup
(setImplicitACLCategories in server.c), plus a small table of rudis-only
commands below.

Usage:
    scripts/gen_acl_categories.py [VALKEY_SRC_DIR] > src/acl_categories.rs
VALKEY_SRC_DIR defaults to ~/valkey.
"""
import glob
import json
import os
import sys

# Bit order follows `ACL CAT` in Redis/Valkey.
CATEGORIES = [
    "keyspace", "read", "write", "set", "sortedset", "list", "hash", "string",
    "bitmap", "hyperloglog", "geo", "stream", "pubsub", "admin", "fast",
    "slow", "blocking", "dangerous", "connection", "transaction", "scripting",
]

# Commands rudis implements that are not in the Valkey table. The ACL layer
# sees these coarse names (see connection::acl_cmd_name / get_cmd_name), so
# multi-operation families are tagged conservatively: anything that can
# modify data is @write (so `-@write` blocks it and `+@read` does not grant
# it), and server-side/agent/network extensions are @admin @dangerous.
EXTRA = {
    # Server/network extensions.
    "agent": ["admin", "dangerous", "slow"],
    "crdt": ["admin", "dangerous", "write", "slow"],
    "dflycluster": ["admin", "dangerous", "slow"],
    "dflymigrate": ["admin", "dangerous", "slow"],
    "llm": ["admin", "dangerous", "slow"],
    "mcp": ["admin", "dangerous", "slow"],
    "tier": ["admin", "dangerous", "slow"],
    "xdp": ["admin", "dangerous", "slow"],
    "stick": ["connection", "slow"],
    "sticky": ["connection", "slow"],
    "unstick": ["connection", "slow"],
    # Data-type families with mixed read/write subcommands.
    "bf": ["write", "slow"],
    "cf": ["write", "slow"],
    "cms": ["write", "slow"],
    "ft": ["write", "slow"],
    "json": ["write", "slow"],
    "semantic": ["write", "slow"],
    "topk": ["write", "slow"],
    # Single commands.
    "blmovem": ["write", "list", "slow", "blocking"],
    "lmovem": ["write", "list", "slow"],
    "delex": ["write", "keyspace", "slow"],
    "increx": ["write", "string", "slow"],
    "digest": ["read", "string", "slow"],
    "sdiffcard": ["read", "set", "slow"],
    "sunioncard": ["read", "set", "slow"],
    "xackdel": ["write", "stream", "slow"],
    "xcfgset": ["write", "stream", "slow"],
    "xdelex": ["write", "stream", "slow"],
    "xidmprecord": ["write", "stream", "slow"],
    "xnack": ["write", "stream", "slow"],
    "vadd": ["write", "slow"],
    "vrem": ["write", "slow"],
    "vsetattr": ["write", "slow"],
    "vcard": ["read", "slow"],
    "vdim": ["read", "slow"],
    "vemb": ["read", "slow"],
    "vgetattr": ["read", "slow"],
    "vinfo": ["read", "slow"],
    "vismember": ["read", "slow"],
    "vlinks": ["read", "slow"],
    "vquery": ["read", "slow"],
    "vrandmember": ["read", "slow"],
    "vsim": ["read", "slow"],
}


def implicit(v):
    cats = {c.lower() for c in v.get("acl_categories", [])}
    flags = set(v.get("command_flags", []))
    if "WRITE" in flags:
        cats.add("write")
    if "READONLY" in flags and "scripting" not in cats:
        cats.add("read")
    if "ADMIN" in flags:
        cats |= {"admin", "dangerous"}
    if "PUBSUB" in flags:
        cats.add("pubsub")
    if "FAST" in flags:
        cats.add("fast")
    if "BLOCKING" in flags:
        cats.add("blocking")
    if "fast" not in cats:
        cats.add("slow")
    return cats, "NO_AUTH" in flags


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/valkey")
    entries = {}
    for fn in sorted(glob.glob(os.path.join(src, "src", "commands", "*.json"))):
        with open(fn) as f:
            for name, v in json.load(f).items():
                full = name.lower()
                if "container" in v:
                    full = v["container"].lower() + "|" + full
                entries[full] = implicit(v)
    if not entries:
        sys.exit(f"no command json found under {src}/src/commands")
    for name, cats in EXTRA.items():
        assert name not in entries, f"{name} is now in the Valkey table"
        entries[name] = (set(cats), False)

    names = sorted(entries)
    index = {n: i for i, n in enumerate(names)}
    out = []
    w = out.append
    w("// @generated by scripts/gen_acl_categories.py from the Valkey command table")
    w("// (src/commands/*.json) plus rudis-only commands. Do not edit by hand.")
    w("")
    w("/// Category names; bit `i` of [`CmdInfo::cats`] is `CATEGORIES[i]`.")
    w("pub const CATEGORIES: &[&str] = &[")
    for c in CATEGORIES:
        w(f'    "{c}",')
    w("];")
    w("")
    w("pub struct CmdInfo {")
    w("    /// Lowercase name; subcommands are `parent|sub`.")
    w("    pub name: &'static str,")
    w("    pub cats: u32,")
    w("    /// Command carries the NO_AUTH flag (exempt from command ACLs).")
    w("    pub no_auth: bool,")
    w("    /// Index of the container command, for subcommands.")
    w("    pub parent: Option<u16>,")
    w("    /// Index range of this container's subcommands (empty otherwise).")
    w("    pub subs: (u16, u16),")
    w("}")
    w("")
    w(f"pub const NUM_COMMANDS: usize = {len(names)};")
    w(f"pub const WORDS: usize = {(len(names) + 63) // 64};")
    w("")
    w("/// Sorted by `name`.")
    w("pub static COMMANDS: [CmdInfo; NUM_COMMANDS] = [")
    for n in names:
        cats, no_auth = entries[n]
        mask = 0
        for c in cats:
            mask |= 1 << CATEGORIES.index(c)
        parent = "None"
        if "|" in n:
            parent = f"Some({index[n.split('|', 1)[0]]})"
        sub_idx = [index[s] for s in names if s.startswith(n + "|")]
        subs = (min(sub_idx), max(sub_idx) + 1) if sub_idx else (0, 0)
        if sub_idx:
            assert sub_idx == list(range(subs[0], subs[1])), n
        w(
            f'    CmdInfo {{ name: "{n}", cats: {mask:#x}, no_auth: {str(no_auth).lower()}, '
            f"parent: {parent}, subs: ({subs[0]}, {subs[1]}) }},"
        )
    w("];")
    print("\n".join(out))


if __name__ == "__main__":
    main()
