#!/usr/bin/env bash
# Runs Redis/Valkey TCL *integration* suites (replication, RDB, AOF, ...)
# against Rudis. Unlike run_redis_test_suite.sh, these suites start their own
# servers: the harness runs `src/redis-server <config file> [args]` from the
# test directory and waits for " PID: <pid> ... Server initialized" in its
# stdout. A wrapper script provides that and execs Rudis with the generated
# config (same PID, so the harness can signal and kill it).
#
# usage: scripts/run_redis_integration_suite.sh integration/replication[,integration/rdb,...]
set -u
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SRC_TEST_DIR="$REPO_ROOT/tests/redis-tests"
# The suites run from a copy of the test tree, so the generated wrapper and
# the patch below never touch the checked-in tree. Logs end up in
# $TEST_DIR/tests/tmp.
TEST_DIR="$REPO_ROOT/target/redis-tests-integ"
SUITES="${1:?usage: $0 suite[,suite...]}"
CLIENTS="${CLIENTS:-1}"
THREADS="${RUDIS_THREADS:-4}"

if [ "${SKIP_BUILD:-0}" != "1" ]; then
    (cd "$REPO_ROOT" && cargo build --release) || exit 1
fi

mkdir -p "$TEST_DIR"
rsync -a --delete --exclude tests/tmp --exclude src/redis-server \
    "$SRC_TEST_DIR/" "$TEST_DIR/" || exit 1
# createComplexDataset, which most replication suites use for write load,
# builds some hashes with HIMPORT (hash templates, unreleased Redis). Rudis
# does not implement it; build those hashes with HSET instead.
sed -i \
    -e 's/^\(\s*\){\*}\$r himport prepare fs f0 f1 f2$/\1# (rudis) no HIMPORT PREPARE/' \
    -e 's/{\*}\$r himport set \$k fs \$v \[randomValue\] \[randomValue\]/{*}$r hset $k f0 $v f1 [randomValue] f2 [randomValue]/' \
    "$TEST_DIR/tests/support/util.tcl"
if grep -q '$r himport' "$TEST_DIR/tests/support/util.tcl"; then
    echo "warning: util.tcl still uses HIMPORT; update the patch in $0" >&2
fi

mkdir -p "$TEST_DIR/src"
# Suites also run redis-cli, redis-benchmark and redis-check-{rdb,aof};
# take them from a Valkey build when one is around (VALKEY_SRC).
VALKEY_SRC="${VALKEY_SRC:-$HOME/valkey-stable/src}"
for tool in cli benchmark check-rdb check-aof; do
    if [ -x "$VALKEY_SRC/valkey-$tool" ]; then
        ln -sf "$VALKEY_SRC/valkey-$tool" "$TEST_DIR/src/redis-$tool"
    fi
done
cat > "$TEST_DIR/src/redis-server" <<EOF
#!/usr/bin/env bash
# Generated by scripts/run_redis_integration_suite.sh: start Rudis in place of
# redis-server. Extra redis-server style "--name value" overrides are passed
# through as config lines appended to a copy of the config file.
conf="\$1"; shift
if [ \$# -gt 0 ]; then
    tmp="\$conf.rudis"
    cp "\$conf" "\$tmp"
    while [ \$# -gt 0 ]; do
        name="\${1#--}"; shift
        val=""
        while [ \$# -gt 0 ] && [ "\${1#--}" = "\$1" ]; do val="\$val \$1"; shift; done
        echo "\$name\$val" >> "\$tmp"
    done
    conf="\$tmp"
fi
echo " PID: \$\$ (rudis wrapper)"
echo "Server initialized"
exec "$REPO_ROOT/target/release/rudis" --config "\$conf" --threads $THREADS --no-pin
EOF
chmod +x "$TEST_DIR/src/redis-server"

cd "$TEST_DIR"
FAILED=()
PASSED=()
IFS=',' read -ra LIST <<< "$SUITES"
for suite in "${LIST[@]}"; do
    echo ">>> Running integration suite: $suite"
    if tclsh test_helper.tcl --clients "$CLIENTS" --ignore-encoding --ignore-digest \
        --tags "-needs:debug -needs:config-rewrite -needs:pfdebug -valgrind" \
        --single "$suite" ${EXTRA_ARGS:-}; then
        PASSED+=("$suite")
    else
        FAILED+=("$suite")
    fi
done
echo "Passed: ${#PASSED[@]} (${PASSED[*]:-})"
echo "Failed: ${#FAILED[@]} (${FAILED[*]:-})"
[ ${#FAILED[@]} -eq 0 ]
